# Generated by Django 6.0.3 on 2026-03-03 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('sender', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('recipient', models.EmailField(blank=True, max_length=254)),
                ('body', models.TextField()),
                ('snippet', models.CharField(blank=True, max_length=300)),
                ('received_at', models.DateTimeField()),
                ('thread_id', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('personal', 'Personal'), ('work', 'Work'), ('risk', 'Risk'), ('billing', 'Billing'), ('unclassified', 'Unclassified')], default='unclassified', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Medium'), (4, 'Low'), (5, 'Minimal')], default=3)),
                ('confidence', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('needs_review', 'Needs Review')], default='pending', max_length=20)),
                ('explanation', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['priority', '-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('label', 'Label'), ('flag', 'Flag'), ('archive', 'Archive'), ('reply_draft', 'Draft Reply'), ('calendar', 'Add to Calendar'), ('escalate', 'Escalate'), ('no_action', 'No Action')], max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('executed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='triage.email')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
